### ISSUE TITLE
logduct todo

### ISSUE THREAD

**Issue by ato** [nla/jvmctl#7]
- [x] CLI options for the daemon
- [x] Socket activation (accept listening socket on stdin)
- [x] Graceful restart/reload (passing open fds and serialized state to successor)
- [x] Close log files that are idle.
- [x] Persist unit name from socket establishment so messages from a now exited process are directed to the right file.
- [x] Daemon handling of secondary pipes like gc logs (logduct-run transfer them but they're currently ignored)
- [ ] Log expiry
- [ ] Decide compression policy
- jvmctl integration
  - [ ] global logruct-run wrapping
  - [ ] log command
  - [ ] status command
- Test failure behaviour
  - [ ] Disk full
  - [ ] Daemon killed
  - [ ] Permission denied writing to log files
  - [ ] Memory leak check
  - [ ] Full system reboot
